version: '3.8'

# path to local docker volumes \\wsl$\docker-desktop-data\version-pack-data\community\docker\volumes
# bootstrap check failure [1] of [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144] see https://stackoverflow.com/a/66547784/10330374

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_STACK_IMAGE_TAG}
    networks:
      - kus-kus-network
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELK_STACK_IMAGE_TAG}
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - kus-kus-network

  fluentd:
    image: kus-kus_fluentd:latest
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - kus-kus-network
    restart: on-failure
    depends_on:
      - elasticsearch

  redis:
    image: redis:6.2.5
    networks:
      - kus-kus-network

  kus-kus-bot:
    image: blink182u2/kus-kus-bot:0.0.4
    networks:
      - kus-kus-network
    environment:
      bot.token: ${BOT_TOKEN}
      bot.username: KusKusDevBot
      bot.receipt.page.size: 10
      spring.redis.host: redis
      api.receipt.url: "http://kus-kus:9658"
      api.image.url: "http://kus-kus-images:11287"
    depends_on:
      - redis
    links:
      - fluentd
    restart: on-failure
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        fluentd-async-connect: "true"
        tag: kus-kus

  kus-kus:
    image: blink182u2/kus-kus:0.0.1-SNAPSHOT
    networks:
      - kus-kus-network
    environment:
      spring.elasticsearch.uris: http://elasticsearch:9200
      server.port: 9658
    depends_on:
      - elasticsearch
    restart: on-failure

  kus-kus-images:
    image: blink182u2/kus-kus-images:0.0.1-SNAPSHOT
    networks:
      - kus-kus-network
    environment:
      server.port: 11287
      spring.profiles.active: local
    volumes:
      - C:/Users/blink/.aws:/home/cnb/.aws
    restart: on-failure

volumes:
  elasticsearch-data:
    external: true

networks:
  kus-kus-network:
    external: true
