logging:
  level:
    com:
      shaidulin:
        kuskusbot: DEBUG
    io:
      lettuce:
        core: DEBUG
    org:
      springframework:
        web:
          reactive:
            function:
              client:
                ExchangeFunctions: TRACE


spring:
  main:
    web-application-type: none
  mvc:
    log-request-details: true